### ISSUE TITLE
Does not `desiredCount` field work?

### ISSUE THREAD

**Issue by jagaapple** [kayac/ecspresso#131]
I tried to change `desiredCount` field in `service.json` and run `ecspresso deploy --update-service --skip-task-definition` , but a count of tasks was not changed.

```diff
   {
-     "desiredCount": 1,
+     "desiredCount": 0,
```

I confirmed that `--tasks` option works fine to scale-in/out, so does not ecspresso support to change `desiredCount` field in JSON for scale-in/out?

Version: 0.16.0

**Comment by fujiwara** [comment]
Thank you for reporting.

This behavior seems to a bug, but applying the `desiredCount` in service definitions at deploy becomes incompatible with previous versions.

I'm planning to release v1 which has some incompatibility with v0.x.
This behavior will be fixed on v1.

**Comment by fujiwara** [comment]
@jagaapple This issue is resolved on v1 branch. Please try v0.99.x

**Comment by jagaapple** [comment]
@fujiwara 
I just confirmed and it works fine! 😄 
Thank you.
