### ISSUE TITLE
What is the correct way to express bool type in .json file?

### ISSUE THREAD

**Issue by S-YOU** [kayac/ecspresso#15]
The following works, 
```
"essential": {{ env `ESSENTIAL` `false` }},
```

But, the file is not a valid json file anymore

![2018-04-27 16 07 29](https://user-images.githubusercontent.com/1001175/39349231-27fb75da-4a35-11e8-99b5-d3a7b37e6ba5.png)

Is this an expected issue?

**Comment by fujiwara** [comment]
This is a limitation caused by JSON format specification 😞 
Actually, task or service definition files for ecspresso are a template to generate a valid JSON.

**Comment by S-YOU** [comment]
Thank you. I thought that JSON file is parsed as JSON. Closing.
