### ISSUE TITLE
feature request: can use only `--command` flag to execute command

### ISSUE THREAD

**Issue by masseater** [kayac/ecspresso#176]
When I want to run any command without changing the task or service definition, I have to use `--overrides` flag at run, and have to prepare json string for it.

So, I would like to add the flag `--command` and be able to execute any command as follows.

`ecspresso run --config config.yaml --command "echo hoge"`

**Comment by fujiwara** [comment]
Now ecspresso v1.4.0 supports `run --overrides-file` to build an overrides option with a template file.

How about this?

overrides.json
```json
{
    "containerOverrides": [
        {
            "name": "foo",
            "command": ["{{ must_env `COMMAND` | json_escape }}"]
        }
    ]
}
```

`ecspresso run` with COMMAND environment variable.
```
$ COMMAND="echo hoge" ecspresso run --overrides-file overrides.json
```
