### ISSUE TITLE
Feature Request: Support specifying a remote state file by s3 URL.

### ISSUE THREAD

**Issue by ebi-yade** [kayac/ecspresso#211]
日本語で失礼致します:bowing_man:
先日Twitterにてリプライした内容について、おこがましいですがIssueを作成致します。

### Use-cases

s3にあるtfstateを参照するとき、 `s3://<bucket-name>/<key-of-file>` 形式で指定できると直感的でわかりやすいと思います。
また同時に、 [Workspaces](https://www.terraform.io/docs/state/workspaces.html) に関して現在 ecspresso ではサポートがないものと存じますが、これステージ分離等に活用している場合も（configファイルを複数設けるなどハードコーディングで）対応できるように感じます。（URLを `s3://<bucket-name>/env:/${terraform.workspace}/<key-of-project>` 形式にする）

### Proposal

これは完全に余談ですが、ユースケースによってはtfstate自体が分離されている可能性もあって、tfstateを複数指定できたら更に良いなとも思います。ただこれは単に配列で取得してJSONをマージしても事故が起こると思われるので、名前をつけてimportする必要がありますが、そこで付与した名前をserviceなどの定義ファイル内で識別子として認識するところも実装する必要がありそうで大変そうなので...自分がまともにGoのコードを開発できるようになってからPR飛ばします...:crying_cat_face:

**Comment by fujiwara** [comment]
v1.3.0 で、tfstate の URL からの読み込みに対応しました。お試しください！
https://github.com/kayac/ecspresso/releases/tag/v1.3.0
