### ISSUE TITLE
Amazon ECR public image [NG] verify with 401 Unauthorized.

### ISSUE THREAD

**Issue by 7474** [kayac/ecspresso#213]
前日リリースされた[Amazon ECR Public Gallery](https://gallery.ecr.aws/)のイメージを指定した task definition を、ECRに未ログインで `verify` したところ `401 Unauthorized` で NG となりました。

期待する動作はECRへの未ログイン時にECR Publicイメージへは匿名アクセスで存在確認が行われる、または `verifySkipErr` などでverify NGとはならない形になります。

NG時の出力:
>TaskDefinition [NG] verify ContainerDefinition[mackerel-container-agent] failed: verify Image[public.ecr.aws/mackerel/mackerel-container-agent:plugins] failed: 401 Unauthorized

イメージをDocker Hubのものに変えただけの差分でのOK出力:
>ContainerDefinition[mackerel-container-agent]
Image[mackerel/mackerel-container-agent:plugins]
--> [OK]

`public.ecr.aws/mackerel/mackerel-container-agent:plugins` は手元のマシンで未認証で docker pull 可能なことを確認しました。

**Comment by fujiwara** [comment]
v1.3.0 で ECR Public を含めた一般の公開イメージの検証に対応しました。お試しください！https://github.com/kayac/ecspresso/releases/tag/v1.3.0

**Comment by 7474** [comment]
ECR public イメージの存在確認取れました。最高です！
```
    ContainerDefinition[mackerel-container-agent]
      Image[public.ecr.aws/mackerel/mackerel-container-agent:plugins]
      --> [OK]
```
