### ISSUE TITLE
Feature Request: Support add Tags to TaskDefinition

### ISSUE THREAD

**Issue by Hirofumi-Narita** [kayac/ecspresso#246]
Hello.

I want to add tag to taskdefinition.
But ecspresso doesn't support to add tags.

Because there are no tags in the argument.

https://github.com/kayac/ecspresso/blob/53d3c283ec696d6abb7b1ca2b21fa1246204af35/diff.go#L108-L122

The AWS SDK RegisterTaskDefinitionInput supports adding tags.
https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#RegisterTaskDefinitionInput
```
Tags []*Tag `locationName:"tags" type:"list"`
```

In my project, I use tags to use billing and AWS Resource Groups services.
So I want this feature.

Thank you.

**Comment by Hirofumi-Narita** [comment]
Type TaskDefinition doesn't have a tags property, so support can be a bit tricky ...

https://github.com/aws/aws-sdk-go/blob/v1.37.11/service/ecs/api.go#L18648

**Comment by fujiwara** [comment]
v1.5.0 released!
