### ISSUE TITLE
Feature Request: Support diff of desiredCount

### ISSUE THREAD

**Issue by cohalz** [kayac/ecspresso#274]
Currently,`diff` command does not cover `desiredCount`.
I want to target desiredCount as well as other parameters so that we can manage changes in `ecs-service-def.json`.
We can also achieve this with `init --force-overwrite`, but this method will not work if you are using templates or jsonnet.

Please add an option like `--enable-desired-count`.

**Comment by fujiwara** [comment]
I'm writing patch #276 for this issue.

The patch works to show the diff of desiredCount only when it is defined in the local service definition.

The desiredCount in the local effects as below.
- Not defined => desiredCount will not apply to remote service by deployment.
- Defined => desiredCount will apply to remote service by deployment.

Is this match for your use cases?

**Comment by cohalz** [comment]
Yes, thank you for the great solution!!

**Comment by fujiwara** [comment]
v1.5.1 released! https://github.com/kayac/ecspresso/releases/tag/v1.5.1
