### ISSUE TITLE
[v1.5.2] MissingRegion: could not find region configuration になる（v1.5.1 では起きない）

### ISSUE THREAD

**Issue by sogaoh** [kayac/ecspresso#286]
https://twitter.com/sogaoh/status/1390165192357466112 でお伝えした問題です

```
ecspresso --config config.yaml verify
2021/05/06 04:34:22 failed to read tfstate: s3://XXXXXXXXXX/YYYYY/ZZZZZ/terraform.tfstate: failed to read tfstate from s3://XXXXXXXXXX/YYYYY/ZZZZZ/terraform.tfstate: MissingRegion: could not find region configuration
```

状況として、AWS_DEFAULT_REGION="ap-southeast-1" を direnv で設定してますが、AWS_REGION は設定していませんでした。

他に確認事項あれば随時ご連絡ください。 @fujiwara

**Comment by fujiwara** [comment]
tfstate-lookup で S3 bucket のリージョン自動判別を入れた際の問題でした https://github.com/fujiwara/tfstate-lookup/pull/24
こちらで修正したので、ecspresso もリリースします 🙏

**Comment by fujiwara** [comment]
@sogaoh https://github.com/kayac/ecspresso/releases/tag/v20210506-6d782bb 修正版を用意してみました。直っているか確認して頂けますでしょうか。

**Comment by sogaoh** [comment]
@fujiwara v20210506-6d782bb で直っていることを確認しました。即対応ありがとうございました。（CloseでOKです。18:00過ぎたら閉じますね）

**Comment by fujiwara** [comment]
ありがとうございます!
