### ISSUE TITLE
fail to find corresponding CodeDeploy deployment group if cluster's full ARN is specified at cluster's value in config.yml

### ISSUE THREAD

**Issue by aereal** [kayac/ecspresso#309]
# Way to reproduce

- Specify full ARN of the cluster at config.yml such as `cluster: arn:aws:ecs:ap-northeast-1:1234567890:cluster/my-cluster`
- Setup service's deployment controller with CodeDeploy
- Run `ecspresso deploy`

# Expected behavior

No errors happen.

# Actual Behavior

Got `failed to find CodeDeploy Application/DeploymentGroup` error:

```
2021/07/23 19:17:02 deploy FAILED. failed to find CodeDeploy Application/DeploymentGroup for ECS service <my-service-name> on cluster arn:aws:ecs:ap-northeast-1:1234567890:cluster/my-cluster
```

# Possible causes

[The `cluster` value in config.yml compared with possible deployment group's ECS cluster value](https://github.com/kayac/ecspresso/blob/46d781219d24fd817989c2ed0fa776a1b163c6ec/deploy.go#L283), but we can specify cluster's full ARN as `cluster` value in config.yml and ecspresso works well except running `ecspresso deploy`.

So if we specified the full ARN, it is never matched with the corresponding deployment group's cluster specification.

I have some ideas about this problem:

- Currently ecspresso [mentioned nothing about `cluster`'s value requirements](https://github.com/kayac/ecspresso#configuration-file)
- We may treat well either short name or full ARN in `cluster` if we extract the short name from them and pass it to `ListDeploymentGroups`'s argument

**Comment by aereal** [comment]
I found the ecspresso lacks some test cases especially `Deploy()` subcommand.
We should add those test cases before fixing this issue.

So I [added those test cases](https://github.com/kayac/ecspresso/compare/v1...aereal:deploy-test) but they consist of bit large changes such as introducing [golang/mock](https://github.com/golang/mock), depending on interfaces instead of concrete constructs, and adding a smart constructor that used to inject AWS clients for testing.

How do you think about [those changes?](https://github.com/kayac/ecspresso/compare/v1...aereal:deploy-test)

**Comment by fujiwara** [comment]
> Currently ecspresso mentioned nothing about cluster's value requirements

Thank you for your reporting!

ECS API accepts an arn as a cluster parameter. However, it does not make actual merits.
I decided cluster's value requires only cluster name (not an arn) in ecspresso config.

I'll update documents about the ecspresso config.

**Comment by fujiwara** [comment]
> How do you think about those changes?

Thank you! This is great but too heavy...

I think ECS will change API's response value (not response structures and types) a possibility after mock tests are introduced. So this mock tests are too heavy for me against a real benefit.

**Comment by aereal** [comment]
> I decided cluster's value requires only cluster name (not an arn) in ecspresso config.

LGTM :shipit: 

> Thank you! This is great but too heavy...

Yeah, I agree. We can run `go:generate` on CI, but it introduces another complexity to this project.
