### ISSUE TITLE
conflict docker logging tags and Replace syntax in the JSON file to environment variable

### ISSUE THREAD

**Issue by yoshihiro-yoshida-biz** [kayac/ecspresso#32]
I write {{.ID}} in docker logging tags, but this conflicts with the function to replace the syntax of JSON file with environment variable. What should I do now?

reference:
docker logging tags,
https://docs.docker.com/config/containers/logging/log_tags/

**Comment by fujiwara** [comment]
How about output `{{.ID}}` as string using text/template syntax as below.
```
{{`{{.ID}}`}}
```

**Comment by yoshihiro-yoshida-biz** [comment]
Thank you very much!!
