### ISSUE TITLE
timeoutを設定したが必ず10分で失敗してしまう

### ISSUE THREAD

**Issue by yoshihiro-yoshida-biz** [kayac/ecspresso#33]
config fileでtimeout: 15mを設定したが、10分後にerrorになって失敗してしまうのですが、なぜでしょうか。error文は下記になります。

```
2019/08/28 06:32:18 deploy FAILED. deploy failed: ResourceNotReady: exceeded wait attempts
Build step 'Execute shell' marked build as failure
```

**Comment by hajimeni** [comment]
おそらく、この行で `WaiterOption` を設定していないからかと。
https://github.com/kayac/ecspresso/blob/master/ecspresso.go#L538

これでTimeOut効くようになるけど、修正方針としてコレでよいかどうかちょっと不明。
https://github.com/hajimeni/ecspresso/commit/697f635f67756165eb38b5c47a12c581ce8d5348

**Comment by fujiwara** [comment]
ありがとうございます。#34 確認しました。15 のハードコードがすこし気持ち悪い(がやむを得なそう)のでコメントを追加しておきます 🙏

**Comment by fujiwara** [comment]
https://github.com/kayac/ecspresso/releases/tag/v0.8.2 v0.8.2 をリリースしました。

**Comment by yoshihiro-yoshida-biz** [comment]
thank you
