### ISSUE TITLE
[Feature Request]  Unlimited terminal width

### ISSUE THREAD

**Issue by winebarrel** [kayac/ecspresso#344]
# My problem

Copying the event log from Terminal is inconvenient because the Terminal width is fixed at 90.
![スクリーンショット 2021-10-16 14 00 47](https://user-images.githubusercontent.com/117768/137574469-988f1fde-8061-454e-b99c-08a968a3e486.png)

# Feature Request

Would you please add "Unlimited terminal width mode" with no line breaks in the event message?

**Comment by fujiwara** [comment]
[v2.0.0](https://github.com/kayac/ecspresso/releases/tag/v2.0.0) released!

**Comment by winebarrel** [comment]
I have verified that the issue is resolved.
Thank you!
