### ISSUE TITLE
extVar support for jsonnet files

### ISSUE THREAD

**Issue by hkdnet** [kayac/ecspresso#350]
Hi,
I'm really excited with the jsonnet support. I can remove jsonnet install step 🙂 
I tried it and found currently there's no way to pass `--ext-str a=b` options.
Do you have plans to support `extVar` related options?

**Comment by fujiwara** [comment]
@hkdnet --ext-str and --ext-code options are supported by v1.7.1.
https://github.com/kayac/ecspresso/releases/tag/v1.7.1

**Comment by hkdnet** [comment]
Great! Thank you ❤️
