### ISSUE TITLE
What does --force-new-deployment option do?

### ISSUE THREAD

**Issue by psyhomb** [kayac/ecspresso#36]
First of all I'd like to say thank you for such a great tool, and keep up a good work! :+1: 

It's not really clear to me at first glance so I would be really thankful if someone could explain it to me what does `--force-new-deployment` option do?
```ecspresso deploy --force-new-deployment```

Is this option perhaps going to force tasks to be stopped, skip the draining part or it is something completely different?

Thanks in advance for your answer! :wave:

**Comment by psyhomb** [comment]
Ok according to AWS Go SDK documentation it's not related to LB draining, it's just going to force a new deployment even if there is no service definition changes.
https://docs.aws.amazon.com/sdk-for-go/api/service/ecs/#ECS.UpdateServiceWithContext

> // Whether to force a new deployment of the service. Deployments are not forced
    // by default. You can use this option to trigger a new deployment with no service
    // definition changes. For example, you can update a service's tasks to use
    // a newer Docker image with the same image/tag combination (my_image:latest)
    // or to roll Fargate tasks onto a newer platform version.

So my question is, is there is a way to force stop of ECS tasks (`running:0`) w/ this tool, w/o need to wait for LB draining to be completed successfully. This is something I would like to implement for dev and test environments.

Thanks

**Comment by fujiwara** [comment]
`--force-new-deployment` only works with `--skip-task-definition` actually. 
If you want to replace all tasks in service without update task definition,  use `--skip-task-definition` and `--force-new-deployment` both.
When a task definition in service is unchanged, ECS does not replace tasks in the service by default.

> So my question is, is there is a way to force stop of ECS tasks (running:0) w/ this tool, w/o need to wait for LB draining to be completed successfully. This is something I would like to implement for dev and test environments.

`--tasks` option is for that use case.  e.g.`ecspresso deploy --skip-task-definiton --tasks 0`

**Comment by psyhomb** [comment]
@fujiware thanks for the quick answer I will try it out this and let you know if it works!
