### ISSUE TITLE
Feature Request: verify container image platform

### ISSUE THREAD

**Issue by konoui** [kayac/ecspresso#380]
Thank you for making a great tool!
I would like to propose a platform verify feature.

### Background
Currently, ECS provides several runtimes.
e.g.
Fargate/EC2 with AMD64/Linux
Fargate/EC2 with ARM64/Linux
Fargate/EC2 with AMD64/Windows

The feature is to verify whether images in task definition support target platform or not.
For example, there is a following task definition.

```
{
    "containerDefinitions": [
        {
            "name": "custom-image"
        }
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "networkMode": "awsvpc",
    "runtimePlatform": {
        "operatingSystemFamily": "LINUX",
        "cpuArchitecture": "ARM64"
    }
}
```

When `custom-image` does not support arm64/linux platform, ECS task will fail to start due to incompatible platform. 
We need to start tasks and check container logs to be aware of failures.

I will try to implement it and create PR.

**Comment by fujiwara** [comment]
[v2.0.0](https://github.com/kayac/ecspresso/releases/tag/v2.0.0) released!
