### ISSUE TITLE
must_env in task definition causes exec command to fail

### ISSUE THREAD

**Issue by tukiyo320** [kayac/ecspresso#389]
# Environment
ecspresso v1.7.8

# Incident
When executing `ecspresso exec` to a task definition that contains `must_env` environment variables, panic occurs due to undefined environment variables.

This did not happen in v1.5.0.

# Expected behavior
Even if must_env is used in a task definition, it should be possible to `ecspresso exec` without setting environment variables at runtime.

# Log
```
$ DEPLOY_TARGET_ENV=prod ecspresso exec --config=.ecspresso/application-config.yml --command="/bin/bash"
panic: template attach failed: template: conf:12:77: executing "conf" at <must_env `DEPLOY_IMAGE_TAG`>: error calling must_env: environment variable DEPLOY_IMAGE_TAG is not defined

goroutine 1 [running]:
github.com/kayac/go-config.readConfigBytes(0xc000372600, 0x5b9, 0x5ba, 0xc00083ed60, 0x5ba, 0x0, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/kayac/go-config@v0.6.0/config.go:149 +0x18e
github.com/kayac/go-config.(*Loader).ReadWithEnv(0xc0003d8180, 0xc0003680f0, 0x24, 0x3a7c600, 0x0, 0x23d, 0xc00083ee08, 0x10187d3)
        /home/runner/go/pkg/mod/github.com/kayac/go-config@v0.6.0/config.go:322 +0xc6
github.com/kayac/ecspresso.(*App).readDefinitionFile(0xc0000bac80, 0xc0003680f0, 0x24, 0x10c1245, 0x10c1d00, 0xc0003685a0, 0xc000293628, 0x0)
        /home/runner/work/ecspresso/ecspresso/util.go:68 +0x6b9
github.com/kayac/ecspresso.(*App).LoadTaskDefinition(0xc0000bac80, 0xc0003680f0, 0x24, 0x25, 0x2374b08, 0xc0002935f0)
        /home/runner/work/ecspresso/ecspresso/ecspresso.go:498 +0x5a
github.com/kayac/ecspresso.(*App).listTasks(0xc0000bac80, 0x236f1a0, 0xc00071d680, 0xc000719d20, 0xc00083f2f8, 0x1, 0x1, 0xc0007143c0, 0x1, 0x1, ...)
        /home/runner/work/ecspresso/ecspresso/tasks.go:64 +0x48b
github.com/kayac/ecspresso.(*App).Exec(0xc0000bac80, 0xc000719d20, 0xc000719d50, 0xc000719d60, 0xc00045f7a0, 0xc00045f790, 0xc00045f798, 0x0, 0x0)
        /home/runner/work/ecspresso/ecspresso/exec.go:53 +0x145
main._main(0xc000094058)
        /home/runner/work/ecspresso/ecspresso/cmd/ecspresso/main.go:293 +0x8cde
main.main()
        /home/runner/work/ecspresso/ecspresso/cmd/ecspresso/main.go:18 +0x25
```

At this time, in our task definition, we set the family, arn, and image URLs as follows. The reason we specify `must_env` is that this is mainly for CD.

```
"family": “my_{{ must_env `DEPLOY_TARGET_ENV` }}_application”,
"taskRoleArn": "arn:aws:iam::hogefuga/components/my_{{ must_env `DEPLOY_TARGET_ENV` }}_application_task_role",

"containerDefinitions": [
  {
    "name": “hoge”,
    "image": “hogehoge.dkr.ecr.ap-northeast-1.amazonaws.com/hoge:{{ must_env `DEPLOY_IMAGE_TAG` }}",

…
```

Also, we have confirmed that if must_env is replaced with env, it can be executed without any problem.

This also happens when the environment variable used by the family is left undefined, so it does not seem to depend on which element uses must_env.

# Workaround
Define a `must_env` environment variable (in our case, `DEPLOY_IMAGE_TAG`) at `ecspresso exec` runtime.

# Possible causes

Probably because the change in v1.6 to allow command execution without ECS service refers to the task definition to find the same family.

**Comment by fujiwara** [comment]
@tukiyo320
Thank you for reporting!

> This did not happen in v1.5.0.

Before v1.6, ecspresso tasks and exec command does not load a local task definition file.
After v1.6, these commands load a local task definition file and evaluate `must_env` in the file. So a panic raised when environment variables are not defined.

I fixed this issue by #390. If config.Service defined, ecspresso looks for a task definition in the ECS service.

Could you try this version?
https://github.com/kayac/ecspresso/releases/tag/v1.7.7-7-g69c85de-2-gefbe5d7-2-gf008a7c

**Comment by tukiyo320** [comment]
@fujiwara 
Thanks for the quick response!
I've confirmed that it works fine with that binary!

**Comment by fujiwara** [comment]
v1.7.10 released! https://github.com/kayac/ecspresso/releases/tag/v1.7.10
