### ISSUE TITLE
init multiple services

### ISSUE THREAD

**Issue by pathcl** [kayac/ecspresso#460]
Hey there!

First thank for this great open source tool. I'd say is one of the few Ive seen pretty well rounded in regards to ECS.

I'm wondering howto use it if I want to init multiple services. Currently I can do:

```
$ ecspresso init --region us-east-1 --cluster my-cluster --service core-non-prod-nginx-test --config ecspresso.yml
```

I'd like to do the same but for all the services at once without any service input. Is it possible? if not I'd like to make it happen.

Thanks again!

**Comment by fujiwara** [comment]
@pathcl I'm sorry for the too-late response.

ecspresso manages an(=single) ECS service and related task definitions by a configuration file (e.g., ecspresso.yml).

If we manage multiple ECS services, place multiple configuration files for each.

To initialize multiple ECS services (named `foo` and `bar`), for example in shell

```
$ for sv in foo bar; ecspresso init --service $sv --config-file-path $sv.yml --task-definition-path taskdef-$sv.json --service-definition-path service-$sv.json; done
```
