### ISSUE TITLE
`ecspress exec` shows STOPPED tasks

### ISSUE THREAD

**Issue by winebarrel** [kayac/ecspresso#528]
When executing ecspresso exec, STOPPED tasks are displayed, making it difficult to find RUNNING tasks.

<img width="967" alt="スクリーンショット 2023-03-05 14 56 08" src="https://user-images.githubusercontent.com/117768/222944332-40df9c50-7390-4991-b793-d334c5f8ab50.png">

Could you please not display STOPPED tasks?

* ecspresso version: 2.0.4

**Comment by fujiwara** [comment]
@winebarrel fixed by 2.0.5 or later. Please try https://github.com/kayac/ecspresso/releases/tag/v2.0.5-nightly-6b91a090c1a52f23bb05aeb2e7ff7d53f8409cfd.

**Comment by winebarrel** [comment]
Thank you!
