### ISSUE TITLE
`ecspresso run` doesn't fail when ECS task failed to start

### ISSUE THREAD

**Issue by itkq** [kayac/ecspresso#534]
`ecspresso run` command waits for the task to exit and then looks at its status and exits with exit code 0 or 1, unless the --no-wait wait or --wait-until=running option is specified. However, if the image is invalid and cannot be pulled for example, the task will not start and the command will exit with exit code 0 because the container doesn't have exit code or reason. Is this behavior intended?

**Comment by fujiwara** [comment]
I think `espresso run` should exit with non-0 status if failed to run a task. So I plan to fix the behavior.

**Comment by fujiwara** [comment]
@itkq fixed by https://github.com/kayac/ecspresso/releases/tag/v2.0.5-nightly-6b91a090c1a52f23bb05aeb2e7ff7d53f8409cfd. Please try it!

**Comment by itkq** [comment]
Thank you! It worked as expected. Looking forward to the official release!
