### ISSUE TITLE
Allow specifying a revision when executing the deploy command

### ISSUE THREAD

**Issue by tksx1227** [kayac/ecspresso#671]
In the deployment flow of our project, there is a step to deploy another service using the same [task-definition:revision] that was used for the existing service.

Therefore, when running the `ecspresso deploy` command, it would be very useful to have the option to deploy with a specific revision specified by the user instead of the most recent revision.

Since the `ecspresso run` command allows you to run a task at a specific revision with the `--revision=<REVISION_NUMBER>` option, I thought it would be possible to specify a revision when deploying a service in the same way.

I will create a PR based on the `run` command implementation, if you would like to review it. Of course, if you see no need to incorporate it, you can close it.

Thank you in advance :)

**Comment by fujiwara** [comment]
@tksx1227 Thank you! v2.3.3 released!
https://github.com/kayac/ecspresso/releases/tag/v2.3.3
