### ISSUE TITLE
Option for non-zero exit status when deployment is rolled back (rolling deployment)

### ISSUE THREAD

**Issue by karaluh** [kayac/ecspresso#732]
Currently, when deploying a service with rolling deployment strategy and the deployment fails and is rolled back, ecspresso exits with a 0 status code. It should exit with a non-zero status code, because the deployment actually failed, or at least provide an option to do so.

**Comment by fujiwara** [comment]
@karaluh Thank you for the reporting!

I agree that behavior is undesirable.

When the circuit breaker is invoked, ECS sends events to EventBridge, but ecspresso cannot capture the events without external AWS services (for example, SQS).
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs_service_deployment_events.html

So, I'm planning to detect the deployment failure by comparing the task definition in the [Deployment](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ecs/types#Deployment) after the service is stable.

**Comment by fujiwara** [comment]
@karaluh v2.4.0-rc1 released! Please try it.
https://github.com/kayac/ecspresso/releases/tag/v2.4.0-rc1

**Comment by karaluh** [comment]
Works as expected, thanks a lot!
