### ISSUE TITLE
request to update github.com/aws/aws-sdk-go-v2/service/ecs version to v1.45.0

### ISSUE THREAD

**Issue by tatsukoni-pra** [kayac/ecspresso#757]
## Background

- Recently, Amazon Elastic Container Services (Amazon ECS) provides the ability to restart containers without requiring a task relaunch.
　- https://aws.amazon.com/jp/about-aws/whats-new/2024/08/amazon-ecs-restart-containers-task-relaunch/
- `github.com/aws/aws-sdk-go-v2/service/ecs` has supported container restart policies since `v1.45.0`
　- https://github.com/aws/aws-sdk-go-v2/blob/release-2024-08-15/service/ecs/CHANGELOG.md#v1450-2024-08-15

**v1.45.0 (2024-08-15)**
```
Feature: This release introduces a new ContainerDefinition configuration to support the customer-managed keys for ECS container restart feature.
```

## Current Issue

- ecspresso is currently using `github.com/aws/aws-sdk-go-v2/service/ecs v1.44.3`
　- https://github.com/kayac/ecspresso/blob/v2/go.mod#L15
- As a result, when attempting to deploy a task definition that includes a container restart policy, the following warning occurs:

```
Warning: /10/21 01:29:47 [WARNING] json: unknown field "RestartPolicy" in task-def.jsonnet
```

![Image](https://github.com/user-attachments/assets/5e7eeefc-e47e-4826-84f4-251169e95712)

- Additionally, after deployment, the container restart policy is not reflected.

![Image](https://github.com/user-attachments/assets/4d1710d3-1e86-42c6-8240-c39a7d3b03cd)

## Request

- We would like to request an update of the `github.com/aws/aws-sdk-go-v2/service/ecs` version used to `v1.45.0`

**Comment by tatsukoni-pra** [comment]
Currently,  we are using ecspresso `v2.4.1`.

**Comment by fujiwara** [comment]
@tatsukoni-pra Thank you for the request!
https://github.com/kayac/ecspresso/releases/tag/v2.4.2 supports `restartPolicy`. Please try it.

**Comment by tatsukoni-pra** [comment]
@fujiwara 
Thank you for your prompt response!!

In ecspresso `v2.4.2`, the warning disappeared and `restartPolicy` could be used and reflected.

![Image](https://github.com/user-attachments/assets/7a35f06b-c757-43bd-95cd-554115304751)
