### ISSUE TITLE
Fail when `ecspresso run --dry-run` in v2.4.2

### ISSUE THREAD

**Issue by rikeda71** [kayac/ecspresso#764]
## version
v2.4.2

## Detail

Command:

```bash
$ ecspresso run --dry-run=true
2024/11/02 09:20:31 [INFO] ecspresso version: v2.4.2
2024/11/02 09:20:31 xxx/yyy Running task
2024/11/02 09:20:31 xxx/yyy Task definition ARN: family business-stg-server-app will be registered
2024/11/02 09:20:31 [ERROR] FAILED. failed to describe task definition: operation error ECS: DescribeTaskDefinition, https response error StatusCode: 400, RequestID: business-stg-server-app, ClientException: Family contains invalid characters.
```

But `business-stg-server-app` family is registered.  Also, this command is success using v2.4.1.

Besides, `ecspresso run` is success using v2.4.2.

In the difference of https://github.com/kayac/ecspresso/compare/v2.4.1...v2.4.2 , the following has changed.

- fixes of `run.go`
  - https://github.com/kayac/ecspresso/pull/750
- version of `github.com/aws/aws-sdk-go-v2/xxx` 

Maybe these are related.
Could you please confirm?

**Comment by fujiwara** [comment]
@rikeda71 Thank you for the reporting!
I have confirmed this issue. Indeed, I broke `run --dry-run` at #750.

I'll fix this problem. Please wait a minute.

**Comment by fujiwara** [comment]
v2.4.3 released!
https://github.com/kayac/ecspresso/releases/tag/v2.4.3

**Comment by rikeda71** [comment]
Thank you so match !
