### ISSUE TITLE
Diff behavior when a service is defined, but service_definition is not defined

### ISSUE THREAD

**Issue by tomoyasuzuki** [kayac/ecspresso#771]
# Problem statement 
I am using v2.3.5 and get the following error when using the ecspresso diff command.

```
2024/11/11 17:29:22 [INFO] ecspresso version: v2.3.5
2024/11/11 17:29:22 [ERROR] FAILED. failed to load service definition: service_definition is not defined
```
# How to reproduce

1. Install ecspresso
2. Create dummy config file like this. 
3. run `ecspresso diff --config test.yaml` 

```
region: ap-northeast-1
cluster: dev
service: test
task_definition: task-def.json
```

# What is a problem ? 

The `diff` command currently only checks the `service` in the config file, but there are cases where the `service` is defined without a `service_definition` (for instance, when configurations possible with `service_definition` are managed via Terraform). Since the `diff` command requires `service_definition` to compare service settings, I think it should also check if `service_definition` is not empty.

If community members agree to this change, I will create a PR.

### current implementation 
```
if d.config.Service != "" {
```

### Ideal implementation
```
if d.config.Service != "" && d.config.ServiceDefinitionPath != "" {
```

**Comment by fujiwara** [comment]
@tomoyasuzuki That is by design.

When the `service` is defined in the config, ecspresso manages the ECS service. So ecspresso requires `service_definition`.

Remove the `service` from the config file to manage task definitions only (without ECS service).

**Comment by tomoyasuzuki** [comment]
>Remove the service from the config file to manage task definitions only (without ECS service)

Understood.  Thanks for your reply !
